<?php

return [
    'enabled' => (bool) env('CATMIN_EDITOR_ENABLED', true),

    'modes' => [
        'simple',
        'rich',
        'rich+assets',
        'structured',
    ],

    'field_definitions' => [
        [
            'scope' => 'pages.*',
            'field' => 'content',
            'mode' => 'structured',
            'media_allowed' => true,
            'snippets' => ['*'],
            'blocks' => ['*'],
            'source' => 'core.pages',
        ],
        [
            'scope' => 'articles.*',
            'field' => 'content',
            'mode' => 'structured',
            'media_allowed' => true,
            'snippets' => ['*'],
            'blocks' => ['*'],
            'source' => 'core.articles',
        ],
        [
            'scope' => 'articles.*',
            'field' => 'excerpt',
            'mode' => 'rich',
            'media_allowed' => false,
            'source' => 'core.articles',
        ],
        [
            'scope' => 'events.*',
            'field' => 'description',
            'mode' => 'structured',
            'media_allowed' => true,
            'snippets' => ['*'],
            'blocks' => ['hero', 'two-columns', 'faq-simple', 'event-card'],
            'requires_addons' => ['cat-event'],
            'source' => 'addon.cat-event',
        ],
        [
            'scope' => 'shop.*',
            'field' => 'description',
            'mode' => 'rich+assets',
            'media_allowed' => true,
            'snippets' => ['*'],
            'blocks' => [],
            'requires_addons' => ['catmin-shop'],
            'source' => 'addon.catmin-shop',
        ],
        [
            'scope' => '*',
            'field' => '*notes*',
            'mode' => 'simple',
            'media_allowed' => false,
            'source' => 'fallback.notes',
        ],
    ],

    'snippet_registry' => [
        [
            'id' => 'cta-button',
            'label' => 'Bouton CTA',
            'icon' => 'bi-cursor',
            'category' => 'cta',
            'html' => '<p><a class="btn btn-primary" href="#">Votre appel a action</a></p>',
            'scopes' => ['*'],
        ],
        [
            'id' => 'info-box',
            'label' => 'Encart info',
            'icon' => 'bi-info-circle',
            'category' => 'messages',
            'html' => '<div class="alert alert-info" role="alert"><strong>Info:</strong> Message court d\'information.</div>',
            'scopes' => ['*'],
        ],
        [
            'id' => 'styled-button',
            'label' => 'Bouton stylé secondaire',
            'icon' => 'bi-hand-index-thumb',
            'category' => 'cta',
            'html' => '<p><a class="btn btn-outline-primary btn-sm" href="#">Action secondaire</a></p>',
            'scopes' => ['*'],
        ],
        [
            'id' => 'simple-banner',
            'label' => 'Bannière simple',
            'icon' => 'bi-layout-text-window-reverse',
            'category' => 'layout',
            'html' => '<section class="p-3 rounded bg-light"><h3 class="h5 mb-1">Titre banniere</h3><p class="mb-0">Texte court.</p></section>',
            'scopes' => ['*'],
        ],
        [
            'id' => 'quote',
            'label' => 'Citation',
            'icon' => 'bi-quote',
            'category' => 'content',
            'html' => '<blockquote class="blockquote"><p>Votre citation.</p><footer class="blockquote-footer">Auteur</footer></blockquote>',
            'scopes' => ['*'],
        ],
        [
            'id' => 'divider',
            'label' => 'Separateur',
            'icon' => 'bi-dash-lg',
            'category' => 'layout',
            'html' => '<hr>',
            'scopes' => ['*'],
        ],
        [
            'id' => 'media-image-card',
            'label' => 'Image card media',
            'icon' => 'bi-image',
            'category' => 'media',
            'html' => '<figure class="card"><img src="https://picsum.photos/900/420" class="card-img-top" alt="Image"><figcaption class="card-body"><p class="card-text">Legende image</p></figcaption></figure>',
            'scopes' => ['*'],
            'requires_modules' => ['media'],
        ],
    ],

    'block_registry' => [
        [
            'id' => 'hero',
            'label' => 'Hero',
            'icon' => 'bi-stars',
            'category' => 'structure',
            'html' => '<section class="p-4 rounded bg-light"><h2 class="mb-2">Titre hero</h2><p class="lead mb-3">Sous-titre ou proposition de valeur.</p><a href="#" class="btn btn-primary">Action</a></section>',
            'scopes' => ['pages.*.content', 'articles.*.content', 'events.*.description'],
        ],
        [
            'id' => 'two-columns',
            'label' => 'Deux colonnes',
            'icon' => 'bi-layout-split',
            'category' => 'structure',
            'html' => '<div class="row g-3"><div class="col-md-6"><h3>Colonne A</h3><p>Contenu colonne A.</p></div><div class="col-md-6"><h3>Colonne B</h3><p>Contenu colonne B.</p></div></div>',
            'scopes' => ['pages.*.content', 'articles.*.content', 'events.*.description'],
        ],
        [
            'id' => 'image-text',
            'label' => 'Image + texte',
            'icon' => 'bi-images',
            'category' => 'structure',
            'html' => '<div class="row g-3 align-items-center"><div class="col-md-5"><img class="img-fluid rounded" src="https://picsum.photos/800/600" alt=""></div><div class="col-md-7"><h3>Titre section</h3><p>Texte de presentation.</p></div></div>',
            'scopes' => ['pages.*.content', 'articles.*.content'],
        ],
        [
            'id' => 'simple-grid',
            'label' => 'Grille simple',
            'icon' => 'bi-grid-3x3-gap',
            'category' => 'structure',
            'html' => '<div class="row g-3"><div class="col-md-4"><div class="card"><div class="card-body">Bloc 1</div></div></div><div class="col-md-4"><div class="card"><div class="card-body">Bloc 2</div></div></div><div class="col-md-4"><div class="card"><div class="card-body">Bloc 3</div></div></div></div>',
            'scopes' => ['pages.*.content', 'articles.*.content'],
        ],
        [
            'id' => 'faq-simple',
            'label' => 'FAQ simple',
            'icon' => 'bi-question-circle',
            'category' => 'structure',
            'html' => '<div class="accordion" id="faqSimpleBlock"><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#faqSimpleQ1">Question 1</button></h2><div id="faqSimpleQ1" class="accordion-collapse collapse show" data-bs-parent="#faqSimpleBlock"><div class="accordion-body">Reponse 1.</div></div></div><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faqSimpleQ2">Question 2</button></h2><div id="faqSimpleQ2" class="accordion-collapse collapse" data-bs-parent="#faqSimpleBlock"><div class="accordion-body">Reponse 2.</div></div></div></div>',
            'scopes' => ['pages.*.content', 'articles.*.content'],
        ],
        [
            'id' => 'event-card',
            'label' => 'Section evenement',
            'icon' => 'bi-calendar-event',
            'category' => 'business',
            'html' => '<section class="card border-primary"><div class="card-body"><h3 class="card-title">Titre evenement</h3><p class="mb-2">Date: JJ/MM/AAAA</p><p class="mb-3">Lieu: Ville</p><a href="#" class="btn btn-primary btn-sm">S\'inscrire</a></div></section>',
            'scopes' => ['pages.*.content', 'articles.*.content', 'events.*.description'],
            'requires_addons' => ['cat-event'],
        ],
        [
            'id' => 'product-card',
            'label' => 'Section produit',
            'icon' => 'bi-bag',
            'category' => 'business',
            'html' => '<section class="card"><div class="card-body"><h3 class="card-title">Nom du produit</h3><p class="text-muted mb-2">Prix: 29.90 EUR</p><p class="mb-3">Description courte.</p><a href="#" class="btn btn-outline-primary btn-sm">Voir produit</a></div></section>',
            'scopes' => ['pages.*.content', 'articles.*.content', 'shop.*.description'],
            'requires_addons' => ['catmin-shop'],
        ],
        [
            'id' => 'slider-hero',
            'label' => 'Hero slider',
            'icon' => 'bi-sliders',
            'category' => 'business',
            'html' => '<section class="p-4 rounded bg-dark text-light"><h2 class="h4 mb-2">Hero Slider</h2><p class="mb-0">Placeholder pour integration slider.</p></section>',
            'scopes' => ['pages.*.content', 'articles.*.content'],
            'requires_addons' => ['catmin-slider'],
        ],
    ],

    'fields' => [
        'pages.create' => [
            'content' => true,
        ],
        'pages.edit' => [
            'content' => true,
        ],
        'articles.create' => [
            'content' => true,
        ],
        'articles.edit' => [
            'content' => true,
        ],
    ],

    'snippets' => [
        ['label' => '[Alert] Info', 'icon' => 'bi-info-circle', 'html' => '<div class="alert alert-info" role="alert"><strong>Information:</strong> Ajoutez votre message.</div>'],
        ['label' => '[Alert] Success', 'icon' => 'bi-check-circle', 'html' => '<div class="alert alert-success" role="alert"><strong>Succes:</strong> Operation validee.</div>'],
        ['label' => '[Alert] Warning', 'icon' => 'bi-exclamation-triangle', 'html' => '<div class="alert alert-warning" role="alert"><strong>Attention:</strong> Verifiez vos donnees.</div>'],
        ['label' => '[Alert] Danger', 'icon' => 'bi-x-circle', 'html' => '<div class="alert alert-danger" role="alert"><strong>Erreur:</strong> Action impossible.</div>'],

        ['label' => '[Card] Simple', 'icon' => 'bi-card-text', 'html' => '<div class="card"><div class="card-body"><h5 class="card-title">Titre</h5><p class="card-text">Description courte.</p></div></div>'],
        ['label' => '[Card] Shadow', 'icon' => 'bi-card-heading', 'html' => '<div class="card shadow"><div class="card-body"><h5 class="card-title">Titre</h5><p class="card-text">Description courte.</p></div></div>'],
        ['label' => '[Card] Grid 3', 'icon' => 'bi-grid-3x3-gap', 'html' => '<div class="row g-3"><div class="col-md-4"><div class="card"><div class="card-body">Card 1</div></div></div><div class="col-md-4"><div class="card"><div class="card-body">Card 2</div></div></div><div class="col-md-4"><div class="card"><div class="card-body">Card 3</div></div></div></div>'],

        ['label' => '[Badge] Group', 'icon' => 'bi-tags', 'html' => '<div class="d-flex gap-2 flex-wrap"><span class="badge bg-primary">Primary</span><span class="badge bg-secondary">Secondary</span><span class="badge bg-success">Success</span><span class="badge bg-warning">Warning</span><span class="badge bg-danger">Danger</span></div>'],

        ['label' => '[List] Group', 'icon' => 'bi-list-ul', 'html' => '<ul class="list-group"><li class="list-group-item">Element 1</li><li class="list-group-item">Element 2</li><li class="list-group-item">Element 3</li></ul>'],
        ['label' => '[List] Group Active', 'icon' => 'bi-list-check', 'html' => '<ul class="list-group"><li class="list-group-item active">Element actif</li><li class="list-group-item">Element 2</li><li class="list-group-item">Element 3</li></ul>'],

        ['label' => '[Accordion] 1 Section', 'icon' => 'bi-chevron-expand', 'html' => '<div class="accordion" id="accOne"><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#accOneItem">Section 1</button></h2><div id="accOneItem" class="accordion-collapse collapse show" data-bs-parent="#accOne"><div class="accordion-body">Contenu de la section.</div></div></div></div>'],
        ['label' => '[Accordion] 3 Sections', 'icon' => 'bi-layout-text-sidebar', 'html' => '<div class="accordion" id="accThree"><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#accA">Section 1</button></h2><div id="accA" class="accordion-collapse collapse show" data-bs-parent="#accThree"><div class="accordion-body">Contenu 1</div></div></div><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accB">Section 2</button></h2><div id="accB" class="accordion-collapse collapse" data-bs-parent="#accThree"><div class="accordion-body">Contenu 2</div></div></div><div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accC">Section 3</button></h2><div id="accC" class="accordion-collapse collapse" data-bs-parent="#accThree"><div class="accordion-body">Contenu 3</div></div></div></div>'],

        ['label' => '[Layout] 2 Colonnes', 'icon' => 'bi-layout-split', 'html' => '<div class="row g-3"><div class="col-md-6"><p>Colonne A</p></div><div class="col-md-6"><p>Colonne B</p></div></div>'],
        ['label' => '[Layout] 3 Colonnes', 'icon' => 'bi-grid-3x2', 'html' => '<div class="row g-3"><div class="col-md-4"><p>Colonne A</p></div><div class="col-md-4"><p>Colonne B</p></div><div class="col-md-4"><p>Colonne C</p></div></div>'],
        ['label' => '[Layout] 4 Colonnes', 'icon' => 'bi-grid-3x3', 'html' => '<div class="row g-3"><div class="col-md-3"><p>A</p></div><div class="col-md-3"><p>B</p></div><div class="col-md-3"><p>C</p></div><div class="col-md-3"><p>D</p></div></div>'],

        ['label' => '[Box] Shadow', 'icon' => 'bi-square', 'html' => '<div class="p-4 rounded shadow"><h5>Titre</h5><p>Contenu avec ombre douce.</p></div>'],
        ['label' => '[Box] Border 4px', 'icon' => 'bi-bounding-box', 'html' => '<div class="p-4 rounded" style="border: 4px solid #374151;"><h5>Titre</h5><p>Bordure personnalisee.</p></div>'],
        ['label' => '[Box] Accent Left', 'icon' => 'bi-text-indent-left', 'html' => '<div class="p-4 rounded" style="border-left: 5px solid #0d6efd;"><h5>Titre</h5><p>Accent bleu a gauche.</p></div>'],

        ['label' => '[Hero] Intro', 'icon' => 'bi-stars', 'html' => '<section class="p-4 rounded bg-light"><h2 class="mb-3">Titre hero</h2><p class="lead mb-3">Introduction courte et impactante.</p><a class="btn btn-primary" href="#">Appel a action</a></section>'],
        ['label' => '[CTA] Bloc Action', 'icon' => 'bi-cursor', 'html' => '<div class="p-3 border rounded bg-light"><h3>Votre titre</h3><p>Votre texte de presentation.</p><p><a class="btn btn-primary" href="#">Bouton action</a></p></div>'],

        ['label' => '[Content] Citation', 'icon' => 'bi-quote', 'html' => '<blockquote class="blockquote"><p>Votre citation ici.</p><footer class="blockquote-footer">Auteur</footer></blockquote>'],
        ['label' => '[Content] Table Tarif', 'icon' => 'bi-table', 'html' => '<table class="table table-bordered"><thead><tr><th>Offre</th><th>Prix/mois</th></tr></thead><tbody><tr><td>Starter</td><td>9 EUR</td></tr><tr><td>Pro</td><td>29 EUR</td></tr></tbody></table>'],
    ],

    'paragraphs' => [
        ['label' => 'Paragraphe', 'html' => '<p>Texte</p>'],
        ['label' => 'Titre H2', 'html' => '<h2>Titre</h2>'],
        ['label' => 'Display Heading', 'html' => '<h1 class="display-5">Titre display</h1>'],
        ['label' => 'Lead', 'html' => '<p class="lead">Texte introductif.</p>'],
        ['label' => 'Petit texte', 'html' => '<small class="text-muted">Texte secondaire.</small>'],
    ],

    'blocks' => [
        ['label' => 'Liste UL', 'html' => '<ul><li>Element 1</li><li>Element 2</li><li>Element 3</li></ul>'],
        ['label' => 'Liste OL', 'html' => '<ol><li>Premier</li><li>Deuxieme</li><li>Troisieme</li></ol>'],
        ['label' => 'Liste Inline', 'html' => '<ul class="list-inline"><li class="list-inline-item">Tag 1</li><li class="list-inline-item">Tag 2</li><li class="list-inline-item">Tag 3</li></ul>'],
        ['label' => 'List Group', 'html' => '<ul class="list-group"><li class="list-group-item">A</li><li class="list-group-item">B</li><li class="list-group-item">C</li></ul>'],
        ['label' => 'Table Base', 'html' => '<table class="table"><thead><tr><th>#</th><th>Colonne</th></tr></thead><tbody><tr><td>1</td><td>Valeur</td></tr></tbody></table>'],
        ['label' => 'Table Striped', 'html' => '<table class="table table-striped"><thead><tr><th>#</th><th>Colonne</th></tr></thead><tbody><tr><td>1</td><td>Valeur</td></tr></tbody></table>'],
        ['label' => 'Table Bordered', 'html' => '<table class="table table-bordered"><thead><tr><th>#</th><th>Colonne</th></tr></thead><tbody><tr><td>1</td><td>Valeur</td></tr></tbody></table>'],
        ['label' => 'Table Responsive', 'html' => '<div class="table-responsive"><table class="table table-hover"><thead><tr><th>#</th><th>Colonne</th></tr></thead><tbody><tr><td>1</td><td>Valeur</td></tr></tbody></table></div>'],
    ],

    'allowed_iframe_hosts' => [],

    'allowed_css_classes' => [
        'alert', 'alert-info', 'alert-warning', 'alert-danger', 'alert-success',
        'btn', 'btn-primary', 'btn-secondary', 'btn-outline-primary',
        'btn-sm', 'badge',
        'btn-group',
        'card', 'card-body', 'card-title', 'card-text', 'card-header',
        'accordion', 'accordion-item', 'accordion-header', 'accordion-button', 'accordion-collapse', 'accordion-body', 'accordion-flush', 'collapsed',
        'collapse', 'show',
        'row', 'col', 'g-2', 'g-3',
        'col-md-3', 'col-md-4', 'col-md-6', 'col-lg-3', 'col-lg-4', 'col-lg-6',
        'p-3', 'p-4', 'mb-2', 'mb-3', 'mb-4', 'rounded', 'rounded-0', 'rounded-1', 'rounded-2', 'rounded-3', 'rounded-pill',
        'border', 'border-0', 'border-1', 'border-2', 'border-3', 'border-4', 'border-5',
        'border-primary', 'border-secondary', 'border-success', 'border-warning', 'border-danger', 'border-info',
        'bg-light', 'text-muted',
        'shadow', 'shadow-sm', 'shadow-lg',
        'blockquote', 'blockquote-footer', 'lead',
        'table', 'table-striped', 'table-bordered', 'table-hover', 'table-dark',
        'table-borderless', 'table-sm', 'table-responsive',
        'list-inline', 'list-inline-item', 'list-group', 'list-group-item', 'active', 'list-unstyled',
        'd-flex', 'd-block', 'gap-2', 'flex-wrap', 'form-check-input', 'me-2', 'mx-auto',
        'float-start', 'float-end', 'align-top', 'align-middle', 'align-bottom',
        'display-5', 'display-6',
        'text-start', 'text-center', 'text-end',
        'bg-dark', 'text-light', 'bg-primary', 'bg-secondary', 'bg-success', 'bg-warning', 'bg-danger', 'bg-info',
        'catmin-bookmarks-floating', 'catmin-bookmarks-auto', 'catmin-bookmarks-title', 'catmin-bookmarks-list', 'catmin-bookmarks-link', 'is-active',
    ],
];
